### ISSUE TITLE
[Question] Dock

### ISSUE THREAD

**Issue by ahrherrera** [daniruiz/Flat-Remix-GNOME-theme#12]
Do you know how you personalized the dock. I need some like this.

Great work!

**Comment by daniruiz** [comment]
With GNOME dash to dock extension https://extensions.gnome.org/extension/307/dash-to-dock/

**Comment by ahrherrera** [comment]
Thank you for you reply. Do you know about theming GRUB2. Because I install a theme (I put the theme into /boot/grub2/theme) and modify on /etc/default/grub and add the path theme.txt.

When I run grub2-mkconfig -o /boot/grub2/grub.cfg

It shows... on each line order not found . I am using Fedora and GRUB2 on dualboot OS EFI

**Comment by daniruiz** [comment]
¿? Well... that question has nothing to do with this theme. Anyway I have never used a theme with GRUB but with rEFInd, so I can't really help you
