### ISSUE TITLE
where can edit the background opacity of the top bar

### ISSUE THREAD

**Issue by christianbueno1** [daniruiz/Flat-Remix-GNOME-theme#13]
I know that is into gnome-shell.css, but what does lines? I would like to reduce the opacity, thanks in advance.

**Comment by axelmeunier** [comment]
you can install the dynamic top bar shell extension and choose the opacity you want :)

**Comment by daniruiz** [comment]
You can change the opacity in gnom-shell.css file in #panel → background-color: rgba(0, 0, 0, 0.2); yo can change the 0.2 to any value from 0 to 1

**Comment by Rafael-Ramblas** [comment]
Is this still possible? I couldn't change it in this way
