### ISSUE TITLE
little bug when clicking on app icon in dock

### ISSUE THREAD

**Issue by axelmeunier** [daniruiz/Flat-Remix-GNOME-theme#14]
Ok it is just a slight imperfection that will probably bother noone but perfection lovers :) See the video joined : when clicking on an app icon in dock, the dock moves a bit... I think that is because the box in which the icon is set loses its rounded angles when clicking.
Awesome theme otherwise, i really love it :)
[flat-remix-bug.zip](https://github.com/daniruiz/Flat-Remix-GNOME-theme/files/620313/flat-remix-bug.zip)

**Comment by axelmeunier** [comment]
ok i found the bug
`/* Menu de apps seleccionado */
.app-well-app:active .overview-icon, .app-well-app:checked .overview-icon,
.app-well-app.app-folder:active .overview-icon,
.app-well-app.app-folder:checked .overview-icon,
.show-apps:active .overview-icon,
.show-apps:checked .overview-icon,
.grid-search-result:active .overview-icon,
.grid-search-result:checked .overview-icon {
	background: black;
	border: 1px; /*instead of 0*/
	box-shadow: inset 0 -2px 0 white;
	border-radius: 0;
}`

**Comment by daniruiz** [comment]
Thank you so much for solving me that bug. Now it is fixed.

**Comment by axelmeunier** [comment]
you're welcome !

2016-12-01 21:38 GMT+01:00 Daniel Ruiz de Alegría <notifications@github.com>
:
