### ISSUE TITLE
Alignment with screen border

### ISSUE THREAD

**Issue by farika** [daniruiz/Flat-Remix-GNOME-theme#15]
Hello,
I use flat remix on my gnome 3.24 but after a system reinstallation the theme does not go to the edge of the screen anymore. I feel he has shrunk ...
I have a 27 "1440p screen with nvidia drivers.

An idea how to solve the problem? The arc gnome shell themes work properly.

Thank you

**Comment by daniruiz** [comment]
After updating to gnome shell 3.24 the theme didn't work properly. Untill now I've managed to fix a few bugs so maybe it works better now for you. If it doesn't, please send me a screenshot so that I can find the error easier.
