### ISSUE TITLE
Frequent icon resizing in the top panel

### ISSUE THREAD

**Issue by swarnendubiswas** [daniruiz/Flat-Remix-GNOME-theme#18]
Hi,

Thanks for the nice theme, I really like your impression of the top panel in Gnome shell. However, one irritating thing that I have been observing is the frequent resizing of the icons in the top panel. Is this by design?

**Comment by daniruiz** [comment]
Hi,
I have never seen that problem and I don't think that could be caused by the theme. Maybe It could be caused by the icon theme. Anyway, what gnome shell version and icon theme are you using? And if you could send me some screenshots it would help me a lot.

**Comment by swarnendubiswas** [comment]
It seems a bit surprising to me as well, but the point is that I have never experienced this with other Gnome shell themes. 
![screenshot from 2017-06-27 19-40-27](https://user-images.githubusercontent.com/7343807/27718669-0a01fe92-5d13-11e7-991f-061bd35fc935.png)
![screenshot from 2017-06-27 19-40-37](https://user-images.githubusercontent.com/7343807/27718670-0a04ccbc-5d13-11e7-8a15-3a67e312d612.png)

In the first picture, the icons are much larger. I thought it might have to do with maximized windows, but I am not sure.

**Comment by daniruiz** [comment]
As you can see the top bar icons on the right that are gnome-shell native don't change their size. The icons on the left are from TaskBar extension and they should be the same size as the right ones. The problem is not of the shell theme but of that extension. Anyway I will try to fix it but I can't promise I it.

**Comment by swarnendubiswas** [comment]
It is possible, but I reported here since it happens only with this theme. Also, the extension is not TaskBar, but instead Dash to Panel.

**Comment by daniruiz** [comment]
I'd never tried Dash to Panel extension. I've just installed it and I can also see that strange resizing that you reported. I really like how the theme looks with that extension so I will try to support it as soon as posible.

**Comment by daniruiz** [comment]
I've just found how to fix it. I've have just uploaded the new version. Tell me if it also works for you so that I can confirm it's solved.

**Comment by swarnendubiswas** [comment]
Nice, will test and let you know.

**Comment by swarnendubiswas** [comment]
It works, thanks for the fix.
