### ISSUE TITLE
Panel font is too small on HiDPI screen

### ISSUE THREAD

**Issue by swarnendubiswas** [daniruiz/Flat-Remix-GNOME-theme#19]
The panel font is reasonable on old laptop screens, but is too small on a newer HiDPI laptop. I am running Ubuntu Gnome 17.04, Gnome shell 3.24 with gtk 3.22.11. Please see the screenshot.
![screenshot from 2017-07-03 12-42-38](https://user-images.githubusercontent.com/7343807/27803106-76b148e0-5fed-11e7-8d97-697f52be05e9.png)

**Comment by daniruiz** [comment]
The font-size adjustment of the theme is designed to fit with the default width the original gnome-shell top bar, which is pretty thin and only shows the hour. Therefor, the font has that size.
If you want to change the font-size of the top-bar with the "Dash to panel" extension it has the option in the configuration window of the extension itself.

**Comment by swarnendubiswas** [comment]
Thanks, that helps.
