### ISSUE TITLE
oomox compatibility request for Flat Remix

### ISSUE THREAD

**Issue by Warmuser** [daniruiz/Flat-Remix-GNOME-theme#20]
Hello, can you compatibilize to oomox your Flat Remix theme? Read these request that I posted to oomox owner: https://github.com/actionless/oomox/issues/94#issuecomment-323549164 :)

**Comment by daniruiz** [comment]
What is oomox?

**Comment by Warmuser** [comment]
@daniruiz it's a Graphical application for generating different color variations of a Numix-based and Flat-Plat themes (GTK2, GTK3), Gnome-Colors and Archdroid icons. See here: https://github.com/actionless/oomox :)

**Comment by daniruiz** [comment]
And how can I do that?

**Comment by Warmuser** [comment]
@daniruiz you should talk with @actionless for this. :)

**Comment by daniruiz** [comment]
But as I've seen oomox is for gtk+ themes. This is not gtk  but a Gnome Shell theme, they are completely different things.

**Comment by actionless** [comment]
@Warmuser i think material design gnome-shell theme is already can be exported by oomox (via Materia style: https://github.com/nana-4/materia-theme/tree/master/src/gnome-shell)

or is there any big difference between this theme gnome-shell theme and the one which i linked above?

**Comment by daniruiz** [comment]
@actionless well the gnome shell theme is only a css file with a few svg pictures. It isn't difficult to modify the colors and some properties. But how are you going to preview it?

**Comment by Warmuser** [comment]
@daniruiz oops I'm sorry. I didn't know it. Anyway I hope CSS settings could be included in someway on @actionless project. If can be possible. PS: Thanks actionless for the notice.
