### ISSUE TITLE
Ubuntu 17.10 shell theme has almost no effect

### ISSUE THREAD

**Issue by Memnarch** [daniruiz/Flat-Remix-GNOME-theme#22]
Hi,
Just installed the Shell-Theme. In Gnome Tweak Tool, i can select it for the shell. The problem is, i can't select anything for the "Applications" theme. Therefore almost everything stays the same :/

EDIT; The Panel for Shutting down for example is styled correctly.

**Comment by daniruiz** [comment]
Which version of gnome shell are you using?

**Comment by Memnarch** [comment]
Don't have the system in front of me right now, but afaik the new Ubuntu 17.10 uses Gnome 3.26 by default.

**Comment by daniruiz** [comment]
This theme is only the shell theme, it has no application theme. Therefore it modifies the design of the app launcher, the top bar and the top bar menus in Gnome Shell, but not the applications theme.
In ubuntu 16.10 if you installed gnome-shell you may have version 3.20 or 3.22, in which the theme should work perfectly.

Anyway if you could send me some screenshots maybe I can help you better.

**Comment by hukacode** [comment]
I guess he meant 17.10 instead of 16:10

**Comment by Memnarch** [comment]
ohhh whoops. Sorry. The Title was wrong o.o

**Comment by Memnarch** [comment]
Okay since SHell and Application-Themes are 2 different things. I understand that this theme does not have much efefct. Yet it looks a bit alien after all. The shell-parts are themed correctly, and the applications are different.
![ubuntudesktop](https://user-images.githubusercontent.com/1398184/32045990-066243fa-ba42-11e7-934a-9412407ae711.png)

**Comment by daniruiz** [comment]
I understand that mistake. It's quite common jajajaja. For GTK+ themes I  usually use [arc  theme](https://github.com/horst3180/arc-theme) or [ant theme](https://www.gnome-look.org/p/1099856/), they are both great.

Anyway, if I have time I'm planing on developing a new Flat Remix gtk theme so that everything follows the same designs :)
