### ISSUE TITLE
Question: Recreate look of last screenshot

### ISSUE THREAD

**Issue by XPanniX** [daniruiz/Flat-Remix-GNOME-theme#23]
This is not an issue, more a question:
I really like the look on the [last screenshot](https://raw.githubusercontent.com/daniruiz/Flat-Remix-GNOME-theme/master/Images/5.png) with the bigger bar in the bottom.
How can I recreate that look?
(I'm running Ubuntu 17.10)

Also, on the other screenshots in the bottom: Is this the Plank or Ubuntu dock?

Thanks in advance :)

**Comment by daniruiz** [comment]
You can get the bottom bar with dash to panel extension https://extensions.gnome.org/extension/1160/dash-to-panel/

On the other screenshots the bottom bar is dash to dock extension:
https://extensions.gnome.org/extension/307/dash-to-dock/

**Comment by XPanniX** [comment]
Thanks alot! 
And sorry for "abusing" the issues for that question

**Comment by daniruiz** [comment]
No problem :) :+1:
