### ISSUE TITLE
"Cancel" not visible in dark theme and miami theme

### ISSUE THREAD

**Issue by dchatterjee172** [daniruiz/Flat-Remix-GNOME-theme#24]
I'm using the dark version of your theme. In the logout window, "cancel" is not visible 
https://imgur.com/a/cJ5Ep
same problem onticed in miami version too

**Comment by dchatterjee172** [comment]
Another area with same problem,
https://imgur.com/a/kOP7G
@daniruiz

**Comment by daniruiz** [comment]
Thanks! :)
I already know about that problem. I haven't modified dialog buttons yet for both dark themes and there are some other things that aren't finished, that's why they are in beta. As soon as I finish it I'll notify you, probably it will be in the next release.

**Comment by dchatterjee172** [comment]
thanks for the heads-up ... 
:)

**Comment by daniruiz** [comment]
Fixed :)
