### ISSUE TITLE
Miami theme is not working

### ISSUE THREAD

**Issue by dchatterjee172** [daniruiz/Flat-Remix-GNOME-theme#25]
Although I have selected the miami version,
the colors of the notification bar has not changed...
https://imgur.com/a/mikKr

**Comment by daniruiz** [comment]
Ups... I think I uploaded the wrong theme.
Try it now and tell me if it works :sweat_smile:

**Comment by dchatterjee172** [comment]
@daniruiz 
Fixed!
Please check out the other two issues
