### ISSUE TITLE
High CPU usage by gnome-shell and cursor lagging 

### ISSUE THREAD

**Issue by dchatterjee172** [daniruiz/Flat-Remix-GNOME-theme#28]
@daniruiz    
in GNOME Shell 3.26.2, after setting into dark miami theme, one can observecursor lagging and high CPU usage by gnome-shell.   
This doesn't happen in the default theme of gnome-shell   
![screenshot from 2017-11-24 21-00-57](https://user-images.githubusercontent.com/10482742/33217344-93097800-d15d-11e7-8ebb-73f01068f059.png)
![screenshot from 2017-11-24 21-00-20](https://user-images.githubusercontent.com/10482742/33217345-9362ee8a-d15d-11e7-8bdf-8a1e14af1a82.png)
![screenshot from 2017-11-24 20-59-21](https://user-images.githubusercontent.com/10482742/33217346-93a45e38-d15d-11e7-968f-753eddafd9c6.png)

**Comment by daniruiz** [comment]
I think it is a wayland error. It also happens to me when I change to other gnome-shell themes (not only mine). Solution: logout and start session with Gnome Xorg.
If it doesn't work, does it also happen to you with other themes?

**Comment by dchatterjee172** [comment]
@daniruiz 
I'll try with xorg and let you know,
Yes this happens with all your 3 themes, but does not happen with the default gnome-shell theme

**Comment by dchatterjee172** [comment]
@daniruiz 
I can confirm that this issue is wayland specific. UI is much smoother in Xorg
