### ISSUE TITLE
Select "Flat Remix" as shell theme in gnome-tweak-tool . Tweak tool is not showing Flat Remix

### ISSUE THREAD

**Issue by avijit1258** [daniruiz/Flat-Remix-GNOME-theme#31]
I am using Ubuntu16.04 . And installed Flat Remix by adding your repository . But gnome-tweak-tool does not showing Flat Remix Theme .

**Comment by daniruiz** [comment]
Hi,
Thanks for writting.

First of all are you talking about the icon theme or the gnome-shell 
theme.
Did the package finished the installation correctly?, I mean, did you 
update after adding the ppa and after did you install the correspondent 
package? The package-names are flat-remix for the icon theme and 
flat-remix-gnome for the shell theme.

**Comment by avijit1258** [comment]
Yes , the package installed successfully . I have installed flat-remix-gnome shell theme . Tweak tools theme options doesn't show up .

**Comment by daniruiz** [comment]
Look in the /usr/share/themes folder, there should be the folders of 
flat-remix. Otherwise something wrong went with the installation.

**Comment by avijit1258** [comment]
I looked in the /usr/share/themes folder and it is there . 
![themes](https://user-images.githubusercontent.com/10563596/34440225-e970a61e-ecdd-11e7-8904-355548e915ca.png)

**Comment by pauranik51** [comment]
I've the same issue, theme is not applying to my ubuntu deskop UI

**Comment by daniruiz** [comment]
Well, after seeing the screenshot now I understand the mistake. This theme is for GNOME Shell, but in your system you are using Unity. Maybe what you want is to change the applications theme (that's the gtk theme). If so, I usually use arc-theme or ant-theme.
