### ISSUE TITLE
I can't find the theme

### ISSUE THREAD

**Issue by alexandrumarcel** [daniruiz/Flat-Remix-GNOME-theme#35]
Hi! I can't apply the theme for some reasons because I can't find it in Gnome Tweak Box.

I tried to see if I'm using GNOME or not with:

`gnome-shell --version`

And I got as output:

`GNOME Shell 3.26.2`

So I think I have GNOME version

I'm on Ubuntu 17.10

**Comment by alexandrumarcel** [comment]
I tried using 

`gsettings set org.gnome.desktop.interface gtk-theme "Flat Remix"`

But all my windows looks like this:

https://imgur.com/a/HMQJF

**Comment by daniruiz** [comment]
This is the Gnome-Shell theme not the gtk one.
You can find the Flat Remix GTK theme here:
https://github.com/daniruiz/Flat-Remix-GTK

**Comment by alexandrumarcel** [comment]
Oh, ok thanks ^^

**Comment by xenophenes** [comment]
@daniruiz any plans to release this for GTK? I'm in love with the dark Miami theme.
